version: '3.8'

services:
  backend:
    build:
      context: ./captcha-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./captcha-backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./captcha-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./captcha-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  captcha-network:
    driver: bridge 